---
bibliography: ../assets/papers.bib
engine: knitr
link-citations: true
highlight-style: github
date: last-modified
date-format: "DD MMM, YYYY"
from: markdown+emoji 
pagetitle: "IBD ODE Disease Model"
footer: "Digital Twins and Reproducibility // [Open-Source Website of IBD Model](https://bastienchassagnol.github.io/COPASI_Team216_Lo2016/)"
footer-logo-link: "https://www.lpsm.paris/"
sc-sb-title: false
slide-number: true
slide-level: 3
header: Made by Quarto Presentations RevealJs
header-logo: logos/logo_biomedx.svg
header-logo-link: "https://bmedx.com/research-teams/artificial-intelligence/team-vpe/"
logo: "logos/lpsm.png"
logo-alt: "LPSM official logo."
fig-align: "center"
repo-actions: [source, edit, issue]
execute:
  echo: true
  eval: true # necessary for rendering mermaid figures
  message: false
  warning: false
  error: false
  freeze: false
# table options
tbl-cap-location: bottom
# document metadata
lang: en-GB
format: 
  revealjs:
    # animation customisation
    transition: fade
    auto-animate-easing: ease-in-out
    auto-animate-duration: 1.0
    lightbox: true
    preview-links: true
    code-link: true
    code-line-numbers: false
    embed-resources: true
    mainfont: "Didact Gothic"
    css: styles.css
    code-fold: true
    theme: 
      - meds-slides-styles.scss
filters: 
  - reveal-header
  - highlight-text
---

###  {#title-slide data-menu-title="Title Slide" background="#053660"}

```{r}
#| label: setup 
#| echo: false
#| eval: true
#| include: false

library(xml2)
library(downlit)
```


[Digital Twins and Reproducibility]{.custom-title}

[Bridging Point-and-Click `COPASI` Software with Open-Source and Flexible R Programming language]{.custom-subtitle2}

::::: columns
::: {.column width="50%"}
[**First Published:** Mar 14, 2025]{.body-text-s .baby-blue-text}
:::

::: {.column width="50%"}
[**Last updated:** `r format(Sys.time(), '%b %d, %Y')`]{.body-text-s .baby-blue-text}
:::
:::::

<hr class="hr-teal">

::::: columns

::: {.column width="20%"}
[Bastien CHASSAGNOL \|]{.custom-subtitle3}<br> [Post-Doc]{.custom-subtitle3}<br> [*LPSM and Laval*]{.body-text-xs}
:::

::: {.column width="20%"}
[Lilija Wehling \|]{.custom-subtitle3}<br> [Ph.D.]{.custom-subtitle3}<br> [*VPE BioMed X Institute*]{.body-text-xs}
:::

::: {.column width="20%"}
[Atreyee Banerjee \|]{.custom-subtitle3}<br> [Ph.D.]{.custom-subtitle3}<br> [*Mainz Universität*]{.body-text-xs}
:::

::: {.column width="20%"}
[Soria Gasparini \|]{.custom-subtitle3}<br> [Ph.D.]{.custom-subtitle3}<br> [*Heidelberg University*]{.body-text-xs}
:::

::: {.column width="20%"}
[Sanjana Balaji Kuttae \|]{.custom-subtitle3}<br> [Computational Biologist (Research Assistant)]{.custom-subtitle3}<br> [*VPE BioMed X Institute*]{.body-text-xs}
:::

:::::


<br>

Slides available on [GitHub {{< fa brands github title="GitHub Octocat logo" >}}](https://github.com/bastienchassagnol/COPASI_Team216_Lo2016/tree/master/vignettes/slides)

---

### Talks' Layout {.slide-title}

::: {.incremental}
- Reproducibility Crisis. :wave:
- IBD ODE Model :clock9:
- IBD Numerical Simulations :clock9:
- `BioModels` database :arrow_down:
:::

# Reproducibility Crisis {.section #reproducibility data-menu-title="Reproducibility Crisis"}

{{< include sections/0-reproducibility-crisis.qmd >}}

# An ODE of the Immune System {.section #ibd-ode data-menu-title="An ODE of the Immune System"}

{{< include sections/1-IBD-Model.qmd >}}

# Personalised medecine applied to Inflammatory Bowel Disease {.section #ibd-models data-menu-title="Simulations of IBD endotypes"}

{{< include sections/2-IBD-simulations.qmd >}}

# `BioModels`: a repository of biological models {.section #biomodels data-menu-title="`BioModels`: a repository of biological models"}

{{< include sections/3-BioModels.qmd >}}


# Conclusion {.section #conclusion data-menu-title="Conclusion"}

###  {#TheEnd data-menu-title="Take-Aways"}

::: {.slide-title .center-text}
Take-Aways:
:::

::: {.incremental}
- `BioModels`, a data platform for storing curated biological models. 
- However, no automated running of code snippets, nor mandatory access to original data
- Hard-coded tools, such as COPASI, enable quick analyses for non-expert audience
- But they're limited in terms of functionalities and flexibility, to be used with caution.
:::


::: {.center-text .body-text-m .gray-text}
This is a Quarto `RevealJS` Presentation. To learn more, visit <https://quarto.org/docs/presentations/revealjs>.
:::

<br>

::: {.footer .body-text-s .gray-text}
*If you see mistakes, please raise a [GitHub issue](https://github.com/bastienchassagnol/CCCSTBench-Book/issues).*
:::

{{< include references.qmd >}}

{{< include _about.qmd >}}

{{< include license.qmd >}}




