project:
  type: website
  output-dir: ../docs
  
  
website:
  title: "ODE Model of Inflammatory Bowel Disease"
  description: |
    This GitHub repository stores the R code and COPASI models for reproducing
    Lo2016's model on Inflammatory Bowel Disease.
  reader-mode: true 
  site-url: "https://bastienchassagnol.github.io/Lo2016_ODE_IBD"
  repo-url: "https://github.com/bastienchassagnol//COPASI_Team216_Lo2016"
  repo-actions: [edit, source, issue]
  repo-branch: master
  open-graph: true
  back-to-top-navigation: true
  page-navigation: true
  # Website general layout
  favicon: assets/img/IBD-disease.jpeg
  announcement: 
    icon: cone-striped
    dismissable: true
    content: "Website under active development"
    type: warning
    position: below-navbar
  navbar:
    pinned: true
    logo: assets/img/IBD-disease.jpeg
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/bastienchassagnol/COPASI_Team216_Lo2016
          - text: Report a Bug
            href:  https://github.com/bastienchassagnol/COPASI_Team216_Lo2016/issues
    left:
      - href: index.qmd
        text: "Overview"
      - href: files.qmd 
        text: "Files"
      - href: GTBioSS_slides.qmd 
        text: "GT BioSS slides"
      - sidebar:curation
    right:
      - icon: folder-symlink
        href: https://bastienchassagnol.github.io/bastien.chassagnol.io/
      - icon: linkedin
        href: https://www.linkedin.com/posts/bastien-chassagnol-677b67140_identifiersorg-activity-7250082014123425793-jItc
      - icon: envelope
        aria-label: email
        href: "mailto:bastien_chassagnol@laposte.net"        
  # Sidebar navigation      
  sidebar:
    - id: curation
      search: true 
      style: "floating"
      title: "Curation"
      contents:
        - text: "Steady State"
          href: reproducibility/steady_state.qmd
        # - text: "PRCC"
        #   href: reproducibility/prcc.qmd
        # - text: "Patient Stratification"
        #   href: reproducibility/patient_stratification.qmd
  page-footer:
    border: true
    left: |
      Powered by [{{< iconify simple-icons:quarto >}} Quarto](https://quarto.org).
    center: |
      &copy; []{#current-year} Bastien CHASSAGNOL.
    right: |
      License: [CC BY NC SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0).

# Execution options        
execute:
  echo: true
  eval: true
  warning: false
  message: false
  error: false
  collapse: true
  freeze: auto
# Table and bibliographic options
tbl-cap-location: bottom
bibliography:
  - assets/packages.bib
  - assets/papers.bib

engine: knitr
editor: source
number-sections: true
toc: true
toc-depth: 4
lang: en-GB
toc-expand: 2
date: last-modified
link-citations: true
highlight-style: github
from: markdown+emoji 
title-block-banner: true # Listing styles
filters:
  - highlight-text


metadata-files:
  - assets/_format.yml
  - assets/_knitr.yml
  - assets/_authors.yml
