project:
  type: website

website:
  title: "ODE Model of Inflammatory Bowel Disease"
  description: |
    This GitHub repository stores the R code and COPASI models for reproducing
    Lo2016's model on Inflammatory Bowel Disease.
  reader-mode: true # Allow the reader to remove the TOC.
  site-url: "https://bastienchassagnol.github.io/Lo2016_ODE_IBD"
  repo-url: "https://github.com/bastienchassagnol//COPASI_Team216_Lo2016"
  # GitHub Links
  repo-actions: [edit, source, issue]
  back-to-top-navigation: true
  page-navigation: true
  # Website general layout
  navbar:
    pinned: true
    logo: assets/img/IBD-disease.jpeg
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/bastienchassagnol/COPASI_Team216_Lo2016
          - text: Report a Bug
            href:  https://github.com/bastienchassagnol/COPASI_Team216_Lo2016/issues
    left:
      - href: index.qmd
        text: "Overview"
      - href: files.qmd 
        text: "Files"
      - href: history.qmd 
        text: "History"
      - href: components.qmd 
        text: "Components"
      - sidebar:curation
    right:
      - icon: folder-symlink
        href: https://bastienchassagnol.github.io/bastien.chassagnol.io/
      - icon: linkedin
        href: https://www.linkedin.com/posts/bastien-chassagnol-677b67140_identifiersorg-activity-7250082014123425793-jItc
      - icon: envelope
        aria-label: email
        href: "mailto:bastien_chassagnol@laposte.net"        
  # Sidebar navigation      
  sidebar:
    - id: curation
      style: "docked"
      title: "Curations"
      href: curation.qmd
      contents: 
        - text: "Steady State"
          href: codes/steady_state.qmd
        - text: "PRCC"
          href: codes/prcc.qmd 
        - text: "Patient Stratification"
          href: codes/patient_stratification.qmd    
  # Footer navigation           
  page-footer:
    border: true
    left: |
      Powered by [{{< iconify simple-icons:quarto >}} Quarto](https://quarto.org).
    center: |
      &copy; []{#current-year} Bastien CHASSAGNOL.
    right: |
      License: [CC BY NC SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0).
        
# not re-run computations if source files have not been modified
execute:
  echo: true
  warning: false
  message: false
  error: false
  collapse: true
#   freeze: true
# Table and bibliographic options
tbl-cap-location: bottom
bibliography:
  - assets/packages.bib
  - assets/papers.bib
toc: true
toc-depth: 4
toc-expand: 2

# General metadata
author:
  - name: Bastien CHASSAGNOL
    affiliation: 
      - Sorbonne University
      - University Laval
    email: bastien_chassagnol@laposte.net
  - name: Atreyee Banerjee
    affiliation: Mainz Universität
    email: banerjeea@mpip-mainz.mpg.de
  - name: Soria Gasparini
    affiliation:  Heidelberg University
    email: oria.gasparini@stud.uni-heidelberg.de
date: last-modified


# Shared HTML format for each page      
format:
  html:
    theme: 
      light: flatly
    lang: en
    date-format: 'dddd[, the] Do [of] MMMM, YYYY'
    # Code specific formatting
    highlight-style: github
    code-link: false
    code-copy: true
    code-fold: true
    code-tools: true # enables to view the source code
    code-annotations: hover
    anchor-sections: true
    footnotes-hover: true

# When visualing original qmd file, which editor should be favoured? 
editor: source