### {data-menu-title="IBD Network"}

[Inflammatory Bowel Disease: an ODE model]{.slide-title2}

IBD ODE network is depicted in @fig-ODE-network.

::: {#fig-ODE-network}

```{mermaid}
 flowchart LR
      A["$$x^2$$"] -->|"$$\sqrt{x+3}$$"| B("$$\frac{1}{2}$$")
      A -->|"$$\overbrace{a+b+c}^{\text{note}}$$"| C("$$\pi r^2$$")
      B --> D("$$x = \begin{cases} a &\text{if } b \\ c &\text{if } d \end{cases}$$")
      C --> E("$$x(t)=c_1\begin{bmatrix}-\cos{t}+\sin{t}\\ 2\cos{t} \end{bmatrix}e^{2t}$$")
```

This is a simple `mermaid` graph.
:::


::: aside
Note the recently published `SBMLNetwork` framework that automates the standardisation visualization of biochemical models, spanning from SBGN Pathways to Metabolic Models and Flux-diffusion processes. Available as an open-source Python package on [Github](https://github.com/sys-bio/SBMLNetwork).
:::


### {data-menu-title="IBD ODEs"}

[Main classes of ODE models, ordered by increasing complexity]{.slide-title2}

- First order equations: 

- Michaelis-Menten equations

- Auto-catalytic and Feedback Models

  - Positive activation
  - negative activation

- Complex combination of several processes, pairing together multiple variables


::: aside
- 80 pre-defined functions in COPASI, from standard Henri-Michaelis-Menten and mass-actions equations, to complex Bi-Uni competitive enzymatic reaction mechanisms 
- Feature for providing user-defined function
- Critical choice of the nature of the reaction either *reversible* or *irreversible* (uni-directional)
:::


