on:
  workflow_dispatch:
  push:
    branches: [main, master]

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Install R version
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.1'

      - name: Install LOCAL Renv R Dependencies
        uses: r-lib/actions/setup-renv@v2
        
      - name: Render Quarto Slides only
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: revealjs
          path: slides/index.qmd
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Render and Publish global website
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: vignettes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
